### ISSUE TITLE
Rename task

### ISSUE THREAD

**Issue by arthurvr** [JuneChiu/Litchi#1]
> The `grunt-contrib` namespace is reserved for tasks maintained by the Grunt team, please name your task something appropriate that avoids that naming scheme.

_http://gruntjs.com/creating-plugins#naming-your-task_

This plugin has been blacklisted from the plugins website for that reason: https://github.com/gruntjs/gruntjs.com/pull/157. If you republish it as `grunt-litchi` (or whatever name you like) it will appear again.

**Comment by JuneChiu** [comment]
@arthurvr Oh, i see !Thanks for your remind~
